import { NavigatorScreenParams } from '@react-navigation/native';

export type RootStackParamList = {
  Home: undefined;
  Settings: undefined;
  AILogo: undefined;
  AILogoCreate: undefined;
  AILogoStyles: undefined;
  AITattoo: undefined;
  AITattooCreate: undefined;
  AITattooStyles: undefined;
  AISignature: undefined;
  AISignatureCreate: undefined;
  AISignatureStyles: undefined;
  AIArt: undefined;
  AIArtCreate: undefined;
  AIArtStyles: undefined;
  AIRoom: undefined;
  AIRoomCreate: undefined;
  AIRoomStyles: undefined;
  AIWallpaper: undefined;
  AIWallpaperCreate: undefined;
  AIWallpaperStyles: undefined;
  AIGarment: undefined;
  AIGarmentCreate: undefined;
  AIGarmentStyles: undefined;
  AIEmoji: undefined;
  AIEmojiCreate: undefined;
  AIEmojiStyles: undefined;
}; 